language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=x86
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-google-google_play_services
  
script:
  # Unit Test
  - ./gradlew test jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)